OLED.init(128, 64)
OLED.writeStringNewLine("Hi Jack !")
basic.forever(function () {
    OLED.writeNum(RTC_DS1307.getTime(RTC_DS1307.TimeType.DAY))
    OLED.writeString(" : ")
    OLED.writeNum(RTC_DS1307.getTime(RTC_DS1307.TimeType.MONTH))
    OLED.writeString(" : ")
    OLED.writeNumNewLine(RTC_DS1307.getTime(RTC_DS1307.TimeType.YEAR))
    OLED.newLine()
    OLED.writeNum(RTC_DS1307.getTime(RTC_DS1307.TimeType.HOUR))
    OLED.writeString(" : ")
    OLED.writeNum(RTC_DS1307.getTime(RTC_DS1307.TimeType.MINUTE))
    basic.pause(5000)
    OLED.clear()
})
